WHEEL_UP add volume +5
WHEEL_DOWN add volume -5

SHIFT+UP seek +60
SHIFT+DOWN seek -60

SHIFT+WHEEL_UP seek +5
SHIFT+WHEEL_DOWN seek -5

CTRL+SHIFT+UP add chapter +1
CTRL+SHIFT+DOWN add chapter -1

UP add volume +5
DOWN add volume -5

CTRL+WHEEL_UP frame-step
CTRL+WHEEL_DOWN frame-back-step

CTRL+1 change-list glsl-shaders toggle "~~/shaders/Anime4K/Anime4K_DarkLines_HQ.glsl"; show-text "Line darkening toggle"
CTRL+2 change-list glsl-shaders toggle "~~/shaders/Anime4K/Anime4K_ThinLines_HQ.glsl"; show-text "Line thinning toggle"

CTRL+0 change-list glsl-shaders clr ""; show-text "Shaders cleared"
CTRL+9 change-list glsl-shaders set "~~/shaders/SSimSuperRes.glsl:~~/shaders/KrigBilateral.glsl:~~/shaders/Anime4K/Anime4K_Denoise_Bilateral_Mean.glsl:~~/shaders/Anime4K/Anime4K_Deblur_DoG.glsl:~~/shaders/antiring.hook:~~/shaders/mpv-prescalers/vulkan/ravu-r4.hook:~~/shaders/mpv-prescalers/vulkan/ravu-lite-r4.hook:~~/shaders/Anime4K/Anime4K_DarkLines_HQ.glsl:~~/shaders/SSimDownscaler.glsl"; show-text "Anime shaders set"
CTRL+8 change-list glsl-shaders set "~~/shaders/SSimSuperRes.glsl:~~/shaders/KrigBilateral.glsl:~~/shaders/antiring.hook:~~/shaders/mpv-prescalers/vulkan/ravu-r4.hook:~~/shaders/mpv-prescalers/vulkan/ravu-r4.hook:~~/shaders/SSimDownscaler.glsl"; show-text "Normal shaders set"

c show-text "${chapter-list}" 1700

a script-binding toggle-osc-auto-always
