[colors]
transparent_background_colors = false
draw_bold_text_with_bright_colors = false

[colors.primary]
foreground = "#c1c3c5"
background = "#0a0f18"

[colors.cursor]
text = "CellBackground"
cursor = "CellForeground"

[colors.vi_mode_cursor]
text = "CellBackground"
cursor = "CellForeground"

[colors.search]
matches = { foreground = "#181818", background = "#ac4242" }
focused_match = { foreground = "#181818", background = "#f4bf75" }

[colors.hints]
start = { foreground = "#181818", background = "#f4bf75" }
end = { foreground = "#181818", background = "#ac4242" }

[colors.line_indicator]
foreground = "None"
background = "None"

[colors.footer_bar]
foreground = "None"
background = "None"

[colors.selection]
text = "CellBackground"
background = "CellForeground"

[colors.normal]
black = "#0a0f18"
red = "#6c4853"
green = "#505562"
yellow = "#545964"
blue = "#8f525d"
magenta = "#6a646e"
cyan = "#9e646e"
white = "#c1c3c5"

[colors.bright]
black = "#59626d"
red = "#6c4853"
green = "#505562"
yellow = "#545964"
blue = "#8f525d"
magenta = "#6a646e"
cyan = "#9e646e"
white = "#c1c3c5"
