[colors]
transparent_background_colors = false
draw_bold_text_with_bright_colors = false

[colors.primary]
foreground = "#b3b9bd"
background = "#101215"

[colors.cursor]
text = "CellBackground"
cursor = "CellForeground"

[colors.vi_mode_cursor]
text = "CellBackground"
cursor = "CellForeground"

[colors.search]
matches = { foreground = "#181818", background = "#ac4242" }
focused_match = { foreground = "#181818", background = "#f4bf75" }

[colors.hints]
start = { foreground = "#181818", background = "#f4bf75" }
end = { foreground = "#181818", background = "#ac4242" }

[colors.line_indicator]
foreground = "None"
background = "None"

[colors.footer_bar]
foreground = "None"
background = "None"

[colors.selection]
text = "CellBackground"
background = "CellForeground"

[colors.normal]
black = "#101215"
red = "#475B67"
green = "#556974"
yellow = "#66747B"
blue = "#77817F"
magenta = "#8a9aa7"
cyan = "#6D7B85"
white = "#b3b9bd"

[colors.bright]
black = "#7d8184"
red = "#475B67"
green = "#556974"
yellow = "#66747B"
blue = "#77817F"
magenta = "#8a9aa7"
cyan = "#6D7B85"
white = "#b3b9bd"
