[font]
normal = { family = "SauceCodePro Nerd Font Mono", style = "Semibold" }
bold = { family = "SauceCodePro Nerd Font Mono", style = "Black" }
# italic = { family = "SauceCodePro Nerd Font Mono", style = "Italic" }
# bold_italic = { family = "SauceCodePro Nerd Font Mono", style = "Semibold Italic" }
size = 10
offset = { x = 1, y = 0 }
glyph_offset = { x = 0, y = 0 }
builtin_box_drawing = true
