[hints]
alphabet = "jfkdls;ahgurieowpq"

[[hints.enabled]]
regex = "(ipfs:|ipns:|magnet:|mailto:|gemini://|gopher://|https://|http://|news:|file:|git://|ssh:|ftp://)[^\u0000-\u001F\u007F-\u009F<>\"\\s{-}\\^⟨⟩`\\\\]+"
hyperlinks = true
post_processing = true
persist = false
command = "xdg-open"
binding = { key = "L", mods = "Control|Shift" }
mouse.enabled = true
