[[keyboard.bindings]]
key = "Space"
mods = "Alt"
mode = "~Search"
action = "ToggleViMode"

[[keyboard.bindings]]
key = "Q"
mode = "Vi|~Search"
action = "ToggleViMode"

[[keyboard.bindings]]
key = "Escape"
mode = "Vi|~Search"
action = "ToggleViMode"

[[keyboard.bindings]]
key = "V"
mods = "Control|Shift"
action = "Paste"

[[keyboard.bindings]]
key = "C"
mods = "Control|Shift"
action = "Copy"

[[keyboard.bindings]]
key = "="
mods = "Control"
action = "IncreaseFontSize"

[[keyboard.bindings]]
key = "-"
mods = "Control"
action = "DecreaseFontSize"

[[keyboard.bindings]]
key = "+"
mods = "Control|Shift"
action = "ResetFontSize"

[[keyboard.bindings]]
key = "ArrowUp"
mods = "Control|Shift"
action = "ScrollHalfPageUp"

[[keyboard.bindings]]
key = "ArrowDown"
mods = "Control|Shift"
action = "ScrollHalfPageDown"

[[keyboard.bindings]]
key = "ArrowUp"
mods = "Shift"
action = "ScrollLineUp"

[[keyboard.bindings]]
key = "ArrowDown"
mods = "Shift"
action = "ScrollLineDown"

[[keyboard.bindings]]
key = "F"
mods = "Control|Shift"
mode = "~Search"
action = "SearchForward"

[[keyboard.bindings]]
key = "B"
mods = "Control|Shift"
mode = "~Search"
action = "SearchBackward"

[[keyboard.bindings]]
key = "Escape"
mode = "Search"
action = "SearchCancel"

[[keyboard.bindings]]
key = "Tab"
mode = "Search"
action = "SearchFocusNext"

[[keyboard.bindings]]
key = "Tab"
mods = "Shift"
mode = "Search"
action = "SearchFocusPrevious"

[[keyboard.bindings]]
key = "T"
mods = "Control|Shift"
action = "SpawnNewInstance"

[[keyboard.bindings]]
key = "N"
mods = "Control|Shift"
command = { program = "sh", args = ["-c", "~/.scripts/alacritty/new-win.sh --horizontal"] }

[[keyboard.bindings]]
key = "N"
mods = "Control|Shift|Alt"
command = { program = "sh", args = ["-c", "~/.scripts/alacritty/new-win.sh --vertical"] }
