[window]
dimensions = { columns = 80, lines = 20 }
position = "None"
padding = { x = 0, y = 0 }
dynamic_padding = false
decorations = "Full"
opacity = 1.0
blur = false
startup_mode = "Windowed"
title = "Alacritty"
dynamic_title = true
class = { instance = "Alacritty", general = "Alacritty" }
decorations_theme_variant = "None"
resize_increments = false
option_as_alt = "None"
level = "Normal"
